import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Store,hash} from '../lib/store.mjs';
import {createBook,step,saveChapter,unlockChapter,exportBook,settings,config,publicConfig} from '../lib/engine.mjs';
import {qualityGate,checkChapter,count,validatePlan} from '../lib/quality.mjs';
import {modelCall,seal,defaults} from '../lib/model.mjs';
const migration=readFileSync(new URL('../drizzle/0000_rare_tenebrous.sql',import.meta.url),'utf8');
function db(file=':memory:') {
  const conn=new DatabaseSync(file);if(!conn.prepare("SELECT name FROM sqlite_master WHERE name='records'").get())conn.exec(migration.replaceAll('--> statement-breakpoint',''));
  return {conn,prepare(sql){const q=conn.prepare(sql);let args=[];return {bind(...a){args=a;return this;},async first(){return q.get(...args)||null;},async all(){return {results:q.all(...args)};},async run(){const r=q.run(...args);return {meta:{changes:Number(r.changes)}};}};}};
}
const fresh=()=>new Store(db(),'test-owner');
const plan=total=>({title:'TEST ONLY / 合成状态机夹具',platform:'番茄小说',candidates:[{title:'甲',engine:'权力竞争'},{title:'乙',engine:'资源分配'},{title:'丙',engine:'关系决裂'}],bible:{premise:'本夹具只用于程序测试，不是小说质量案例'},style:{narration:'合成'},characters:[{name:'甲'},{name:'乙'},{name:'丙'},{name:'丁'}],facts:{权限:'无'},arcs:Array.from({length:Math.ceil(total/10)},(_,i)=>({id:i+1,start:i*10+1,end:Math.min(total,i*10+10),goal:'阶段'+i,irreversibleChange:'权力改变'+i})),contracts:Array.from({length:total},(_,i)=>({number:i+1,title:'测试章'+i,goal:'推进'+i,consequence:'后果'+i,method:'方法'+i}))});
function synthetic(seed,size){let n=seed+7,s='';for(let i=0;i<size;i++){n=(n*1664525+1013904223)>>>0;s+=String.fromCharCode(0x4e00+n%6000);if(i%80===79)s+='。\n';}return s;}
function review(c,n){const quote=c.content.slice(0,12);const scores=Object.fromEntries([['commercial',18],['causality',18],['character',18],['pace',13],['language',13],['originality',9]].map(([k,score])=>[k,{score,quote,reason:'TEST ONLY: 仅验证数据门，不能代表文学质量'}]));return {scores,issues:[],deleteTest:{necessary:true,loss:'移除将缺少状态'+n},changes:[{key:'章'+n,from:null,to:'已发生',reason:'夹具事件',quote}],summary:'推进'+n,signature:{conflict:'冲突'+n,solution:'手段'+n,emotion:'体验'+n},foreshadowing:[],consequences:'后果'+n,questions:'下一目标'};}
async function fixture(store,cfg,b,prompt,role){const cs=await store.list('chapter',b.id),c=cs.sort((a,b)=>a.number-b.number).find(c=>c.status!=='locked');if(role==='plan')return plan(b.totalChapters);if(role==='contract')return {title:c.title,goal:'推进',deleteLoss:'状态改变',scenes:Array.from({length:Math.ceil(b.targetWords/1600)},()=>({goal:'推动',consequence:'产生代价'}))};if(role==='write')return {text:synthetic(c.number*17+c.chunks.length,b.targetWords/c.contract.scenes.length),sceneComplete:true};if(role==='review')return review(c,c.number);throw new Error('unsupported');}
async function book(store,words=1000,total=3,key=crypto.randomUUID()){return createBook(store,{targetWords:words,totalChapters:total},key);}
async function writeOne(store,b){for(let i=0;i<25;i++){await step(store,b.id,'',fixture);const locked=(await store.list('chapter',b.id)).filter(c=>c.status==='locked');if(locked.length)return locked[0];}throw new Error('not locked');}

test('创建幂等，不覆盖原作品；默认支持100章9000字',async()=>{const s=fresh(),key=crypto.randomUUID();const a=await createBook(s,{},key),b=await createBook(s,{title:'不能覆盖'},key);assert.equal(a.id,b.id);assert.equal(b.totalChapters,100);assert.equal(b.targetWords,9000);assert.equal((await s.list('book')).length,1);});
test('完整规划验证拒绝换皮方案、缺失中段与缺失合同',()=>{assert.equal(validatePlan(plan(100),100).contracts.length,100);const p=plan(100);p.contracts.pop();assert.throws(()=>validatePlan(p,100));const q=plan(100);q.candidates[1].engine=q.candidates[0].engine;assert.throws(()=>validatePlan(q,100));});
test('三章闭环：生成、审核、锁定、状态、导出（合成夹具）',async()=>{const s=fresh(),b=await book(s);for(let i=0;i<15;i++)await step(s,b.id,'',fixture);const cs=await s.list('chapter',b.id);assert.equal(cs.filter(c=>c.status==='locked').length,3);assert.ok(cs.every(c=>c.gate.score===89));const txt=await exportBook(s,b.id);assert.match(txt,/第3章/);assert.ok(txt.startsWith('\ufeff'));});
test('9000字分段中断，保留前两段，只续写缺失片段',async()=>{const s=fresh(),b=await book(s,9000);for(let i=0;i<4;i++)await step(s,b.id,'',fixture);const before=(await s.list('chapter',b.id))[0];assert.equal(before.chunks.length,2);await assert.rejects(step(s,b.id,'',async()=>{throw new Error('网络中断');}),/网络中断/);const mid=await s.get(before.id);assert.equal(mid.content,before.content);assert.equal(mid.lease,null);await step(s,b.id,'',fixture);const after=await s.get(before.id);assert.equal(after.chunks.length,3);assert.ok(after.content.startsWith(before.content));for(let i=0;i<4;i++)await step(s,b.id,'',fixture);assert.equal((await s.get(before.id)).status,'locked');assert.equal(count((await s.get(before.id)).content),9000);});
test('重启数据库仍能从原片段继续；正文与状态均持久化',async()=>{const dir=mkdtempSync(join(tmpdir(),'novel-test-')),path=join(dir,'test.sqlite');try{const d=db(path),s=new Store(d,'test-owner'),b=await book(s);await step(s,b.id,'',fixture);await step(s,b.id,'',fixture);d.conn.close();const restored=new Store(db(path),'test-owner');assert.equal((await restored.get(b.id)).plan.contracts.length,3);await step(restored,b.id,'',fixture);assert.equal((await restored.list('chapter',b.id))[0].status,'reviewing');restored.db.conn.close();}finally{rmSync(dir,{recursive:true});}});
test('并发续写同一检查点只运行一次',async()=>{const s=fresh(),b=await book(s);await step(s,b.id,'',fixture);await step(s,b.id,'',fixture);let release;const gate=new Promise(r=>release=r);const first=step(s,b.id,'',async(...a)=>{await gate;return fixture(...a);});await new Promise(r=>setTimeout(r,20));await assert.rejects(step(s,b.id,'',fixture),/正在执行/);release();await first;assert.equal((await s.list('chapter',b.id))[0].chunks.length,1);});
test('旧租约结果不能覆盖恢复后新任务',async()=>{const s=fresh(),b=await book(s);let release;const gate=new Promise(r=>release=r);const pending=step(s,b.id,'',async(...a)=>{await gate;return fixture(...a);});await new Promise(r=>setTimeout(r,20));const active=await s.get(b.id);await s.save(active,{...active,lease:{token:'replacement',until:Date.now()+10000}});release();await assert.rejects(pending,/租约已变化/);assert.equal((await s.get(b.id)).plan,null);});
test('程序拒绝明显重复、相同剧情指纹和事实冲突',()=>{const content=synthetic(31,1000),c={content,review:{signature:{conflict:'调查',solution:'找线索',emotion:'惊讶'},changes:[{key:'存活',from:'是',to:'否',reason:'变化',quote:content.slice(0,12)}]}};const issues=checkChapter(c,[{number:1,content,review:c.review}],{存活:'否'},1000);assert.ok(issues.some(i=>i.code==='TEXT_LOOP'));assert.ok(issues.some(i=>i.code==='STRUCTURE_LOOP'));assert.ok(issues.some(i=>i.code==='CONTINUITY'));});
test('高分缺少实际原文证据、删除损失或重大问题，不能定稿',()=>{const c={content:synthetic(1,1000)};c.review=review(c,1);c.review.scores.language.quote='不存在的引用';assert.equal(qualityGate(c,[],{},1000).pass,false);c.review=review(c,1);c.review.issues=[{severity:'major',message:'人物行为失真'}];assert.equal(qualityGate(c,[],{},1000).pass,false);c.review=review(c,1);c.review.deleteTest.necessary=false;assert.equal(qualityGate(c,[],{},1000).pass,false);});
test('三轮返修后停止，保存原稿，不无限调用',async()=>{const s=fresh(),b=await book(s);const reject=async(...a)=>{const out=await fixture(...a);if(a[4]==='review')out.issues=[{severity:'major',message:'TEST ONLY: 架构失败'}];return out;};for(let i=0;i<30;i++){try{await step(s,b.id,'',reject);}catch{break;}if((await s.list('chapter',b.id))[0]?.status==='blocked')break;}const c=(await s.list('chapter',b.id))[0];assert.equal(c.status,'blocked');assert.equal(c.attempt,3);assert.ok(c.content.length);const revisions=(await s.list('version',b.id));assert.ok(revisions.length>=1);await assert.rejects(step(s,b.id,'',fixture),/三轮返修/);});
test('编辑保留历史版本；锁定事实不能被后续章节破坏',async()=>{const s=fresh(),b=await book(s),c=await writeOne(s,b);await assert.rejects(saveChapter(s,{id:c.id,revision:c.revision,content:'覆盖'}),/不可直接覆盖/);const unlocked=await unlockChapter(s,c.id);const edited=await saveChapter(s,{id:c.id,revision:unlocked.revision,content:synthetic(23,1000)});assert.equal(edited.review,null);assert.equal(edited.status,'reviewing');assert.ok((await s.list('version',b.id)).some(v=>v.content===c.content));});
test('导出遇到哈希不匹配停止，不输出损坏正文',async()=>{const s=fresh(),b=await book(s),c=await writeOne(s,b);await s.save(c,{...c,content:c.content+'篡改'});await assert.rejects(exportBook(s,b.id),/校验失败/);});
test('API密钥AES-GCM加密；读取配置不包含密钥',async()=>{const s=fresh(),secret=btoa(String.fromCharCode(...crypto.getRandomValues(new Uint8Array(32))));await settings(s,{apiKey:'test-secret-key'},secret);const cfg=await config(s);assert.notEqual(cfg.apiKeyEncrypted,'test-secret-key');assert.equal(await seal(cfg.apiKeyEncrypted,secret,true),'test-secret-key');assert.equal(publicConfig(cfg).apiKeyEncrypted,undefined);await settings(s,{provider:'groq'},secret);assert.equal((await config(s)).apiKeyEncrypted,'');});
test('未授权费用、未知单价和预算超限均在HTTP之前拒绝',async()=>{const s=fresh(),b=await book(s),secret=btoa(String.fromCharCode(...crypto.getRandomValues(new Uint8Array(32))));const cfg={...defaults,spendEnabled:true,inputPrice:1,outputPrice:1,apiKeyEncrypted:await seal('x',secret),monthLimit:0};let called=0;const fetcher=async()=>{called++;};await assert.rejects(modelCall(s,cfg,b,'prompt','write',secret,fetcher),/额度不足/);assert.equal(called,0);assert.equal((await s.cost(b.id)).calls.length,0);await assert.rejects(modelCall(s,{...cfg,spendEnabled:false},b,'prompt','write',secret,fetcher),/尚未开启/);await assert.rejects(modelCall(s,{...cfg,inputPrice:null},b,'prompt','write',secret,fetcher),/单价/);});
test('模型超时保留费用预留；缺失usage不冒充免费',async()=>{const s=fresh(),b=await book(s),secret=btoa(String.fromCharCode(...crypto.getRandomValues(new Uint8Array(32))));const cfg={...defaults,spendEnabled:true,inputPrice:1,outputPrice:1,apiKeyEncrypted:await seal('x',secret)};await assert.rejects(modelCall(s,cfg,b,'prompt','write',secret,async()=>{throw new Error('timeout');}),/timeout/);const cost=await s.cost(b.id);assert.equal(cost.calls[0].status,'uncertain');assert.ok(cost.total>0);const out=await modelCall(s,cfg,b,'prompt','write',secret,async()=>Response.json({choices:[{message:{content:'{"ok":true}'},finish_reason:'stop'}]}));assert.equal(out.ok,true);assert.ok((await s.cost(b.id)).calls.every(c=>c.status==='uncertain'));});
test('多用户数据隔离；CAS拒绝过期编辑请求',async()=>{const d=db(),a=new Store(d,'a'),b=new Store(d,'b'),c=await book(a);assert.equal(await b.get(c.id),null);assert.equal((await b.list('book')).length,0);await a.save(c,{...c,title:'new'});await assert.rejects(a.save(c,{...c,title:'stale'}),/其他任务/);});
