import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Store,hash} from '../lib/store.mjs';
import {createBook,step,saveChapter,unlockChapter,exportBook,settings,config,publicConfig,savePlan,testConnection,setBookBudget} from '../lib/engine.mjs';
import {qualityGate,checkChapter,count,validatePlan} from '../lib/quality.mjs';
import {modelCall,seal,defaults,callSpec} from '../lib/model.mjs';
import {startJob,pauseJob,runJobStep,tickRunner,runnerStatus} from '../lib/jobs.mjs';
import {restoreBackup} from '../lib/backup.mjs';
import {planningRange,validatePlanningDraft} from '../lib/planning.mjs';
import {contractPrompt} from '../lib/prompts.mjs';
const migration=readFileSync(new URL('../drizzle/0000_rare_tenebrous.sql',import.meta.url),'utf8');
function db(file=':memory:') {
  const conn=new DatabaseSync(file);if(!conn.prepare("SELECT name FROM sqlite_master WHERE name='records'").get())conn.exec(migration.replaceAll('--> statement-breakpoint',''));
  return {conn,prepare(sql){const q=conn.prepare(sql);let args=[];return {bind(...a){args=a;return this;},async first(){return q.get(...args)||null;},async all(){return {results:q.all(...args)};},async run(){const r=q.run(...args);return {meta:{changes:Number(r.changes)}};}};}};
}
const fresh=()=>new Store(db(),'test-owner');
const plan=total=>({title:'TEST ONLY / 合成状态机夹具',platform:'番茄小说',candidates:[{title:'甲',engine:'权力竞争'},{title:'乙',engine:'资源分配'},{title:'丙',engine:'关系决裂'}],bible:{premise:'本夹具只用于程序测试，不是小说质量案例'},style:{narration:'合成'},characters:[{name:'甲'},{name:'乙'},{name:'丙'},{name:'丁'}],facts:{权限:'无'},arcs:Array.from({length:Math.ceil(total/10)},(_,i)=>({id:i+1,start:i*10+1,end:Math.min(total,i*10+10),goal:'阶段'+i,irreversibleChange:'权力改变'+i})),contracts:Array.from({length:total},(_,i)=>({number:i+1,title:'测试章'+i,goal:'推进'+i,consequence:'后果'+i,method:'方法'+i}))});
function synthetic(seed,size){let n=seed+7,s='';for(let i=0;i<size;i++){n=(n*1664525+1013904223)>>>0;s+=String.fromCharCode(0x4e00+n%6000);if(i%80===79)s+='。\n';}return s;}
function review(c,n){const quote=c.content.slice(0,12);const scores=Object.fromEntries([['commercial',18],['causality',18],['character',18],['pace',13],['language',13],['originality',9]].map(([k,score])=>[k,{score,quote,reason:'TEST ONLY: 仅验证数据门，不能代表文学质量'}]));return {scores,issues:[],deleteTest:{necessary:true,loss:'移除将缺少状态'+n},changes:[{key:'章'+n,from:null,to:'已发生',reason:'夹具事件',quote}],summary:'推进'+n,signature:{conflict:'冲突'+n,solution:'手段'+n,emotion:'体验'+n},foreshadowing:[],consequences:'后果'+n,questions:'下一目标'};}
async function fixture(store,cfg,b,prompt,role){const cs=await store.list('chapter',b.id),c=cs.sort((a,b)=>a.number-b.number).find(c=>c.status!=='locked');if(role==='plan')return plan(b.totalChapters);if(role==='contract')return {title:c.title,goal:'推进',deleteLoss:'状态改变',scenes:Array.from({length:Math.ceil(b.targetWords/1600)},()=>({goal:'推动',consequence:'产生代价'}))};if(role==='write')return {text:synthetic(c.number*17+c.chunks.length,b.targetWords/c.contract.scenes.length),sceneComplete:true};if(role==='review')return review(c,c.number);throw new Error('unsupported');}
async function book(store,words=1000,total=3,key=crypto.randomUUID()){return createBook(store,{targetWords:words,totalChapters:total},key);}
async function writeOne(store,b){for(let i=0;i<25;i++){await step(store,b.id,'',fixture);const locked=(await store.list('chapter',b.id)).filter(c=>c.status==='locked');if(locked.length)return locked[0];}throw new Error('not locked');}

test('创建幂等，不覆盖原作品；默认支持100章9000字',async()=>{const s=fresh(),key=crypto.randomUUID();const a=await createBook(s,{},key),b=await createBook(s,{title:'不能覆盖'},key);assert.equal(a.id,b.id);assert.equal(b.totalChapters,100);assert.equal(b.targetWords,9000);assert.equal((await s.list('book')).length,1);});
test('完整规划验证拒绝换皮方案、缺失中段与缺失合同',()=>{assert.equal(validatePlan(plan(100),100).contracts.length,100);const p=plan(100);p.contracts.pop();assert.throws(()=>validatePlan(p,100));const q=plan(100);q.candidates[1].engine=q.candidates[0].engine;assert.throws(()=>validatePlan(q,100));});
test('三章闭环：生成、审核、锁定、状态、导出（合成夹具）',async()=>{const s=fresh(),b=await book(s);for(let i=0;i<15;i++)await step(s,b.id,'',fixture);const cs=await s.list('chapter',b.id);assert.equal(cs.filter(c=>c.status==='locked').length,3);assert.ok(cs.every(c=>c.gate.score===89));const txt=await exportBook(s,b.id);assert.match(txt,/第3章/);assert.ok(txt.startsWith('\ufeff'));});
test('9000字分段中断，保留前两段，只续写缺失片段',async()=>{const s=fresh(),b=await book(s,9000);for(let i=0;i<4;i++)await step(s,b.id,'',fixture);const before=(await s.list('chapter',b.id))[0];assert.equal(before.chunks.length,2);await assert.rejects(step(s,b.id,'',async()=>{throw new Error('网络中断');}),/网络中断/);const mid=await s.get(before.id);assert.equal(mid.content,before.content);assert.equal(mid.lease,null);await step(s,b.id,'',fixture);const after=await s.get(before.id);assert.equal(after.chunks.length,3);assert.ok(after.content.startsWith(before.content));for(let i=0;i<4;i++)await step(s,b.id,'',fixture);assert.equal((await s.get(before.id)).status,'locked');assert.equal(count((await s.get(before.id)).content),9000);});
test('重启数据库仍能从原片段继续；正文与状态均持久化',async()=>{const dir=mkdtempSync(join(tmpdir(),'novel-test-')),path=join(dir,'test.sqlite');try{const d=db(path),s=new Store(d,'test-owner'),b=await book(s);await step(s,b.id,'',fixture);await step(s,b.id,'',fixture);d.conn.close();const restored=new Store(db(path),'test-owner');assert.equal((await restored.get(b.id)).plan.contracts.length,3);await step(restored,b.id,'',fixture);assert.equal((await restored.list('chapter',b.id))[0].status,'reviewing');restored.db.conn.close();}finally{rmSync(dir,{recursive:true});}});
test('并发续写同一检查点只运行一次',async()=>{const s=fresh(),b=await book(s);await step(s,b.id,'',fixture);await step(s,b.id,'',fixture);let release;const gate=new Promise(r=>release=r);const first=step(s,b.id,'',async(...a)=>{await gate;return fixture(...a);});await new Promise(r=>setTimeout(r,20));await assert.rejects(step(s,b.id,'',fixture),/正在执行/);release();await first;assert.equal((await s.list('chapter',b.id))[0].chunks.length,1);});
test('旧租约结果不能覆盖恢复后新任务',async()=>{const s=fresh(),b=await book(s);let release;const gate=new Promise(r=>release=r);const pending=step(s,b.id,'',async(...a)=>{await gate;return fixture(...a);});await new Promise(r=>setTimeout(r,20));const active=await s.get(b.id);await s.save(active,{...active,lease:{token:'replacement',until:Date.now()+10000}});release();await assert.rejects(pending,/租约已变化/);assert.equal((await s.get(b.id)).plan,null);});
test('程序拒绝明显重复、相同剧情指纹和事实冲突',()=>{const content=synthetic(31,1000),c={content,review:{signature:{conflict:'调查',solution:'找线索',emotion:'惊讶'},changes:[{key:'存活',from:'是',to:'否',reason:'变化',quote:content.slice(0,12)}]}};const issues=checkChapter(c,[{number:1,content,review:c.review}],{存活:'否'},1000);assert.ok(issues.some(i=>i.code==='TEXT_LOOP'));assert.ok(issues.some(i=>i.code==='STRUCTURE_LOOP'));assert.ok(issues.some(i=>i.code==='CONTINUITY'));});
test('高分缺少实际原文证据、删除损失或重大问题，不能定稿',()=>{const c={content:synthetic(1,1000)};c.review=review(c,1);c.review.scores.language.quote='不存在的引用';assert.equal(qualityGate(c,[],{},1000).pass,false);c.review=review(c,1);c.review.issues=[{severity:'major',message:'人物行为失真'}];assert.equal(qualityGate(c,[],{},1000).pass,false);c.review=review(c,1);c.review.deleteTest.necessary=false;assert.equal(qualityGate(c,[],{},1000).pass,false);});
test('三轮返修后停止，保存原稿，不无限调用',async()=>{const s=fresh(),b=await book(s);const reject=async(...a)=>{const out=await fixture(...a);if(a[4]==='review')out.issues=[{severity:'major',message:'TEST ONLY: 架构失败'}];return out;};for(let i=0;i<30;i++){try{await step(s,b.id,'',reject);}catch{break;}if((await s.list('chapter',b.id))[0]?.status==='blocked')break;}const c=(await s.list('chapter',b.id))[0];assert.equal(c.status,'blocked');assert.equal(c.attempt,3);assert.ok(c.content.length);const revisions=(await s.list('version',b.id));assert.ok(revisions.length>=1);await assert.rejects(step(s,b.id,'',fixture),/三轮返修/);});
test('编辑保留历史版本；锁定事实不能被后续章节破坏',async()=>{const s=fresh(),b=await book(s),c=await writeOne(s,b);await assert.rejects(saveChapter(s,{id:c.id,revision:c.revision,content:'覆盖'}),/不可直接覆盖/);const unlocked=await unlockChapter(s,c.id);const edited=await saveChapter(s,{id:c.id,revision:unlocked.revision,content:synthetic(23,1000)});assert.equal(edited.review,null);assert.equal(edited.status,'reviewing');assert.ok((await s.list('version',b.id)).some(v=>v.content===c.content));});
test('导出遇到哈希不匹配停止，不输出损坏正文',async()=>{const s=fresh(),b=await book(s),c=await writeOne(s,b);await s.save(c,{...c,content:c.content+'篡改'});await assert.rejects(exportBook(s,b.id),/校验失败/);});
test('API密钥AES-GCM加密；读取配置不包含密钥',async()=>{const s=fresh(),secret=btoa(String.fromCharCode(...crypto.getRandomValues(new Uint8Array(32))));await settings(s,{apiKey:'test-secret-key'},secret);const cfg=await config(s);assert.notEqual(cfg.apiKeyEncrypted,'test-secret-key');assert.equal(await seal(cfg.apiKeyEncrypted,secret,true),'test-secret-key');assert.equal(publicConfig(cfg).apiKeyEncrypted,undefined);await settings(s,{provider:'groq'},secret);assert.equal((await config(s)).apiKeyEncrypted,'');});
test('未授权费用、未知单价和预算超限均在HTTP之前拒绝',async()=>{const s=fresh(),b=await book(s),secret=btoa(String.fromCharCode(...crypto.getRandomValues(new Uint8Array(32))));const cfg={...defaults,spendEnabled:true,inputPrice:1,outputPrice:1,apiKeyEncrypted:await seal('x',secret),monthLimit:0};let called=0;const fetcher=async()=>{called++;};await assert.rejects(modelCall(s,cfg,b,'prompt','write',secret,fetcher),/额度不足/);assert.equal(called,0);assert.equal((await s.cost(b.id)).calls.length,0);await assert.rejects(modelCall(s,{...cfg,spendEnabled:false},b,'prompt','write',secret,fetcher),/尚未开启/);await assert.rejects(modelCall(s,{...cfg,inputPrice:null},b,'prompt','write',secret,fetcher),/单价/);});
test('模型超时保留费用预留；缺失usage不冒充免费',async()=>{const s=fresh(),b=await book(s),secret=btoa(String.fromCharCode(...crypto.getRandomValues(new Uint8Array(32))));const cfg={...defaults,spendEnabled:true,inputPrice:1,outputPrice:1,apiKeyEncrypted:await seal('x',secret)};await assert.rejects(modelCall(s,cfg,b,'prompt','write',secret,async()=>{throw new Error('timeout');}),/timeout/);const cost=await s.cost(b.id);assert.equal(cost.calls[0].status,'uncertain');assert.ok(cost.total>0);const out=await modelCall(s,cfg,b,'prompt','write',secret,async()=>Response.json({choices:[{message:{content:'{"ok":true}'},finish_reason:'stop'}]}));assert.equal(out.ok,true);assert.ok((await s.cost(b.id)).calls.every(c=>c.status==='uncertain'));});
test('多用户数据隔离；CAS拒绝过期编辑请求',async()=>{const d=db(),a=new Store(d,'a'),b=new Store(d,'b'),c=await book(a);assert.equal(await b.get(c.id),null);assert.equal((await b.list('book')).length,0);await a.save(c,{...c,title:'new'});await assert.rejects(a.save(c,{...c,title:'stale'}),/其他任务/);});
test('完整备份恢复保留正文/状态/版本；重复恢复不产生第二副本',async()=>{const s=fresh(),b=await book(s);await writeOne(s,b);const backup={format:'novel-factory-backup-v1',book:await s.get(b.id),chapters:await s.list('chapter',b.id),versions:await s.list('version',b.id),audits:[]};const key=crypto.randomUUID();const restored=await restoreBackup(s,backup,key),again=await restoreBackup(s,backup,key);assert.equal(restored.id,again.id);assert.notEqual(restored.id,b.id);assert.equal(restored.status,'paused');assert.equal((await s.list('chapter',restored.id))[0].content,backup.chapters[0].content);assert.equal((await s.list('version',restored.id)).length,backup.versions.length);assert.equal((await s.list('book')).length,2);});
test('备份导入途中故障可用同一标识恢复，损坏备份在创建前拒绝',async()=>{const s=fresh(),b=await book(s);await writeOne(s,b);const backup={format:'novel-factory-backup-v1',book:await s.get(b.id),chapters:await s.list('chapter',b.id),versions:await s.list('version',b.id)};const key=crypto.randomUUID(),create=s.create.bind(s);let fail=true;s.create=async(...args)=>{if(args[0]==='version'&&fail){fail=false;throw new Error('import interrupted');}return create(...args);};await assert.rejects(restoreBackup(s,backup,key),/interrupted/);const restored=await restoreBackup(s,backup,key);assert.equal(restored.restoreComplete,true);assert.equal((await s.list('book')).length,2);const damaged=structuredClone(backup);damaged.chapters[0].content+='损坏';await assert.rejects(restoreBackup(s,damaged,crypto.randomUUID()),/校验失败/);assert.equal((await s.list('book')).length,2);});
test('已知不适用自动正文的平台在调用模型前拒绝',async()=>{const s=fresh(),b=await createBook(s,{platform:'晋江文学城',targetWords:1000,totalChapters:3},crypto.randomUUID());let invoked=0;await assert.rejects(step(s,b.id,'',async()=>{invoked++;}),/不适用自动正文/);assert.equal(invoked,0);});
test('空草稿备份可恢复；架构问题和虚构旧事实不能被高分盖过',async()=>{const s=fresh(),b=await book(s);await step(s,b.id,'',fixture);await s.create('chapter',{number:1,content:'',chunks:[],status:'contract',hash:null,attempt:0},b.id);const backup={format:'novel-factory-backup-v1',book:await s.get(b.id),chapters:await s.list('chapter',b.id)};const restored=await restoreBackup(s,backup,crypto.randomUUID());assert.equal((await s.list('chapter',restored.id))[0].content,'');const c={content:synthetic(1,1000)};c.review=review(c,1);c.review.architectureConcern='主线已经失效';assert.equal(qualityGate(c,[],{},1000).pass,false);c.review=review(c,1);c.review.changes[0].from='凭空声称此前已拥有';assert.ok(qualityGate(c,[],{},1000).issues.some(i=>i.code==='INVENTED_PRIOR'));});

// Cloud-runner and provider compatibility checks use synthetic fixtures only.
async function configured(store,extra={}){const secret=btoa(String.fromCharCode(...crypto.getRandomValues(new Uint8Array(32))));await settings(store,{apiKey:'TEST ONLY / not a real key',inputPrice:1,outputPrice:1,spendEnabled:true,...extra},secret);return secret;}
test('豆包使用已核对的Ark地址、JSON模式、关闭思考和总输出token上限',async()=>{const s=fresh(),b=await book(s),secret=await configured(s,{provider:'doubao',model:'TEST-DOUBAO-ENDPOINT'});let seen;const c=await config(s);const out=await modelCall(s,c,b,'只返回JSON {"ok":true}','write',secret,async(url,options)=>{seen={url,options,body:JSON.parse(options.body)};return Response.json({choices:[{message:{content:'{"ok":true}'},finish_reason:'stop'}],usage:{prompt_tokens:20,completion_tokens:10}});});assert.equal(out.ok,true);assert.equal(seen.url,'https://ark.cn-beijing.volces.com/api/v3/chat/completions');assert.equal(seen.body.max_completion_tokens,4500);assert.equal(seen.body.max_tokens,undefined);assert.equal(seen.body.thinking.type,'disabled');assert.equal(seen.body.response_format.type,'json_object');assert.equal(seen.options.redirect,'error');assert.equal((await s.cost(b.id)).calls[0].status,'settled');});
test('连接测试最多64输出token，未授权不会请求；OpenAI推理模型不传温度',async()=>{const s=fresh();let calls=0;await assert.rejects(testConnection(s,'',modelCall),/尚未开启/);const secret=await configured(s);const result=await testConnection(s,secret,async(...a)=>modelCall(...a,async(url,options)=>{calls++;assert.equal(JSON.parse(options.body).max_tokens,64);return Response.json({choices:[{message:{content:'{"ok":true}'},finish_reason:'stop'}],usage:{prompt_tokens:12,completion_tokens:5}});}));assert.equal(result.ok,true);assert.equal(calls,1);assert.ok(result.cost>0);const spec=callSpec({...defaults,provider:'openai',model:'gpt-5-test-only'},'x','plan');assert.equal(spec.body.max_completion_tokens,16000);assert.equal(spec.body.temperature,undefined);});
test('云端启动须有已保存密钥、价格和费用授权；重复启动不重置目标',async()=>{const s=fresh(),b=await book(s);await assert.rejects(startJob(s,b.id,3),/请先保存/);await configured(s);const a=await startJob(s,b.id,3),again=await startJob(s,b.id,2);assert.equal(a.id,again.id);assert.equal(again.targetChapters,3);assert.equal(again.revision,a.revision);await assert.rejects(step(s,b.id,'',fixture),/云端任务已接管/);});
test('无前台页面，独立云端调用完成三章并在目标处停止（合成夹具）',async()=>{const s=fresh(),b=await book(s,9000);const secret=await configured(s);await startJob(s,b.id,3);for(let i=0;i<50;i++){await tickRunner(s.db,secret,fixture);if((await s.get(b.id+':job')).status==='completed')break;}const cs=await s.list('chapter',b.id);assert.equal(cs.length,3);assert.ok(cs.every(c=>c.status==='locked'&&count(c.content)===9000));const j=await s.get(b.id+':job');assert.equal(j.status,'completed');assert.equal(j.steps,25);let calls=0;const idle=await tickRunner(s.db,secret,async()=>{calls++;});assert.equal(idle.stopReason,'idle');assert.equal(calls,0);assert.ok((await runnerStatus(s.db)).lastTick);});
test('云端进程中断和数据库重开，从原9000字章节缺失片段恢复',async()=>{const dir=mkdtempSync(join(tmpdir(),'novel-cloud-')),path=join(dir,'test.sqlite');let reopened;try{const d=db(path),s=new Store(d,'test-owner'),b=await book(s,9000),secret=await configured(s);await startJob(s,b.id,3);for(let i=0;i<4;i++)await tickRunner(d,secret,fixture);const c=(await s.list('chapter',b.id))[0],j=await s.get(b.id+':job');assert.equal(c.chunks.length,2);await s.save(j,{...j,status:'running',lease:{token:'dead-process',until:Date.now()-1}});await s.save(c,{...c,lease:{token:'dead-chapter',until:Date.now()-1}});d.conn.close();reopened=db(path);const restored=new Store(reopened,'test-owner');await tickRunner(reopened,secret,fixture);const after=await restored.get(c.id);assert.equal(after.chunks.length,3);assert.ok(after.content.startsWith(c.content));assert.equal((await restored.get(j.id)).lease,null);}finally{reopened?.conn.close();rmSync(dir,{recursive:true});}});
test('两个云端执行器并发，不重复规划或重复收费',async()=>{const s=fresh(),b=await book(s),secret=await configured(s);await startJob(s,b.id,3);let release,calls=0;const gate=new Promise(r=>release=r);const pending=runJobStep(s,b.id,secret,async(...a)=>{calls++;await gate;return fixture(...a);});await new Promise(r=>setTimeout(r,20));const other=await tickRunner(s.db,secret,async()=>{calls++;});assert.equal(other.advanced,false);release();await pending;assert.equal(calls,1);assert.equal((await s.get(b.id+':job')).steps,1);});
test('暂停中的模型请求最多保存当前检查点，规划完成不覆盖暂停状态',async()=>{const s=fresh(),b=await book(s),secret=await configured(s);await startJob(s,b.id,3);let release,calls=0;const gate=new Promise(r=>release=r);const pending=runJobStep(s,b.id,secret,async(...a)=>{calls++;await gate;return fixture(...a);});await new Promise(r=>setTimeout(r,20));await pauseJob(s,b.id);release();await pending;assert.equal((await s.get(b.id)).status,'paused');assert.equal((await s.get(b.id+':job')).status,'paused');const idle=await tickRunner(s.db,secret,async()=>{calls++;});assert.equal(idle.stopReason,'idle');assert.equal(calls,1);assert.ok((await s.get(b.id)).plan);});
test('配置变化使云端任务停下，不静默更换模型；检查后可重新启动',async()=>{const s=fresh(),b=await book(s),secret=await configured(s);await startJob(s,b.id,3);await settings(s,{model:'NEW-TEST-MODEL'},secret);let calls=0;const stopped=await tickRunner(s.db,secret,async()=>{calls++;});assert.equal(stopped.stopReason,'changed');assert.equal((await s.get(b.id+':job')).status,'blocked');assert.equal(calls,0);await startJob(s,b.id,3);await tickRunner(s.db,secret,fixture);assert.ok((await s.get(b.id)).plan);});
test('云端预算不足在HTTP前阻止；失败任务不会无限自动重试',async()=>{const s=fresh(),b=await book(s),secret=await configured(s,{taskLimit:.000001});await startJob(s,b.id,3);let calls=0;await tickRunner(s.db,secret,(...a)=>modelCall(...a,async()=>{calls++;throw new Error('should not reach HTTP');}));const j=await s.get(b.id+':job');assert.equal(j.status,'blocked');assert.match(j.error,/超过单次上限/);for(let i=0;i<3;i++)await tickRunner(s.db,secret,()=>{calls++;});assert.equal(calls,0);assert.equal((await s.cost(b.id)).calls.length,0);});
test('云端架构或正式质量审核失败，保留正文并阻止后章',async()=>{const s=fresh(),b=await book(s),secret=await configured(s);await startJob(s,b.id,3);const bad=async(...a)=>{const r=await fixture(...a);if(a[4]==='review')r.architectureConcern='TEST ONLY: 核心故事不可持续';return r;};for(let i=0;i<8;i++)await tickRunner(s.db,secret,bad);const j=await s.get(b.id+':job'),cs=await s.list('chapter',b.id);assert.equal(j.status,'blocked');assert.equal(cs.length,1);assert.equal(cs[0].status,'blocked');assert.ok(cs[0].content);});
test('未来大纲可保存版本、进入提示词和备份；已开始合同不可覆盖',async()=>{const s=fresh(),b=await book(s);const c=await writeOne(s,b);const current=await s.get(b.id),contracts=structuredClone(current.plan.contracts);contracts[1].goal='TEST ONLY: 从调查转向交易';const saved=await savePlan(s,{id:b.id,revision:current.revision,contracts,arcs:current.plan.arcs,guidance:'TEST ONLY: 未来阶段必须承担真实代价'});assert.equal(saved.planRevision,2);assert.equal(saved.guidanceFromChapter,2);assert.equal((await s.get(c.id)).content,c.content);assert.equal((await s.list('planVersion',b.id)).length,1);let prompt='';await step(s,b.id,'',async(...a)=>{prompt=a[3];return fixture(...a);});assert.match(prompt,/未来阶段必须承担真实代价/);const now=await s.get(b.id),bad=structuredClone(now.plan.contracts);bad[0].goal='不能覆盖历史';await assert.rejects(savePlan(s,{id:b.id,revision:now.revision,contracts:bad,arcs:now.plan.arcs,guidance:''}),/已经开始/);const backup={format:'novel-factory-backup-v1',book:now,chapters:await s.list('chapter',b.id),versions:await s.list('version',b.id),planVersions:await s.list('planVersion',b.id)};const restored=await restoreBackup(s,backup,crypto.randomUUID());assert.equal(restored.planRevision,2);assert.equal((await s.list('planVersion',restored.id)).length,1);assert.equal(restored.status,'paused');});
test('云端活动及未保存检查点禁止改大纲；他人不能启动或编辑本书',async()=>{const s=fresh(),b=await book(s),secret=await configured(s);await step(s,b.id,'',fixture);const current=await s.get(b.id),input={id:b.id,revision:current.revision,contracts:current.plan.contracts,arcs:current.plan.arcs,guidance:''};await startJob(s,b.id,3);await assert.rejects(savePlan(s,input),/先暂停/);const other=new Store(s.db,'other-user');await assert.rejects(startJob(other,b.id,3),/作品不存在/);await assert.rejects(savePlan(other,input),/尚未完成/);await pauseJob(s,b.id);const j=await s.get(b.id+':job');await s.save(j,{...j,lease:{token:'still-in-flight',until:Date.now()+10000}});await assert.rejects(savePlan(s,{...input,revision:(await s.get(b.id)).revision}),/先暂停/);});
test('崩溃后过期调用标为费用不确定，不退还预留或再次调用模型',async()=>{const s=fresh();await s.db.prepare('INSERT INTO calls (id,owner,book,month,amount,status,data,created) VALUES (?,?,?,?,?,?,?,?)').bind('dead-call',s.owner,'dead-book','2026-10',123456,'reserved','{}',Date.now()-160000).run();let invoked=0;await tickRunner(s.db,'',()=>{invoked++;});const c=await s.cost('dead-book');assert.equal(c.calls[0].status,'uncertain');assert.equal(c.total,.123456);assert.equal(invoked,0);});

// V0.3 planning fixtures remain synthetic; no supplier or fiction quality claim.
async function batchedFixture(store,cfg,b,prompt,role,...rest){
  if(role==='plan_batch'){const {start,end}=planningRange(b.planningDraft);return {contracts:Array.from({length:end-start+1},(_,i)=>{const number=start+i;return {number,title:'TEST ONLY '+number,goal:'目标'+number,cause:'因果'+number,conflict:'冲突'+number,method:'手段'+number,consequence:'后果'+number,emotion:'体验'+number,hook:'问题'+number};})};}
  return fixture(store,cfg,b,prompt,role,...rest);
}
test('100章规划先保存骨架，再10章一批，全书计划完整前不创建正文',async()=>{
  const s=fresh(),b=await book(s,9000,100),roles=[];
  const invoke=async(...a)=>{roles.push(a[4]);return batchedFixture(...a);};
  const first=await step(s,b.id,'',invoke);assert.equal(first.phase,'plan_outline');assert.equal(first.book.plan,null);assert.equal(first.book.planningDraft.contracts.length,0);
  for(let i=1;i<=10;i++){const r=await step(s,b.id,'',invoke);assert.equal((await s.list('chapter',b.id)).length,0);if(i<10){assert.equal(r.phase,'plan_batch');assert.equal(r.book.planningDraft.contracts.length,i*10);await validatePlanningDraft(r.book.planningDraft,100);}else{assert.equal(r.phase,'plan');assert.equal(r.book.plan.contracts.length,100);assert.equal(r.book.planningDraft,null);}}
  assert.equal(roles.filter(r=>r==='plan').length,1);assert.equal(roles.filter(r=>r==='plan_batch').length,10);
  await step(s,b.id,'',invoke);assert.equal((await s.list('chapter',b.id))[0].status,'writing');assert.equal(roles.at(-1),'contract');
});
test('300章分批规划不会要求单次输出300项；最后不足10章按实际范围保存',async()=>{
  for(const total of [300,23]){const s=fresh(),b=await book(s,1000,total);let prompt='';await step(s,b.id,'',async(...a)=>{prompt=a[3];return batchedFixture(...a);});assert.match(prompt,/不输出逐章contracts/);for(let i=0;i<Math.ceil(total/10);i++)await step(s,b.id,'',batchedFixture);const saved=await s.get(b.id);assert.equal(saved.plan.contracts.length,total);assert.equal(saved.plan.contracts.at(-1).number,total);}
  const spec=callSpec(defaults,'TEST ONLY','plan_batch');assert.equal(spec.maxTokens,6000);assert.equal(spec.model,defaults.model);
});
test('规划途中数据库重开，不重复骨架或已保存批次',async()=>{
  const dir=mkdtempSync(join(tmpdir(),'novel-planning-')),path=join(dir,'test.sqlite');let reopened;
  try{const d=db(path),s=new Store(d,'test-owner'),b=await book(s,9000,100);for(let i=0;i<3;i++)await step(s,b.id,'',batchedFixture);const before=(await s.get(b.id)).planningDraft;assert.equal(before.contracts.length,20);d.conn.close();reopened=db(path);const restored=new Store(reopened,'test-owner');let prompt='';await step(restored,b.id,'',async(...a)=>{assert.equal(a[4],'plan_batch');prompt=a[3];return batchedFixture(...a);});const after=(await restored.get(b.id)).planningDraft;assert.equal(after.contracts.length,30);assert.deepEqual(after.contracts.slice(0,20),before.contracts);assert.deepEqual(after.outline,before.outline);assert.match(prompt,/第21到30章/);}finally{reopened?.conn.close();rmSync(dir,{recursive:true});}
});
test('缺失/越界批次和不连续阶段拒绝提交，不覆盖已经保存的规划',async()=>{
  const s=fresh(),b=await book(s,1000,23);await assert.rejects(step(s,b.id,'',async(...a)=>{const p=await batchedFixture(...a);p.arcs[1].start=9;return p;}),/阶段范围/);assert.equal((await s.get(b.id)).planningDraft,undefined);
  await step(s,b.id,'',batchedFixture);await step(s,b.id,'',batchedFixture);const before=(await s.get(b.id)).planningDraft;
  for(const damage of ['missing','range']){await assert.rejects(step(s,b.id,'',async(...a)=>{const r=await batchedFixture(...a);if(damage==='missing')r.contracts.pop();else r.contracts[0].number=1;return r;}),/本批章节/);assert.deepEqual((await s.get(b.id)).planningDraft,before);}
  const record=await s.get(b.id),corrupt=structuredClone(record.planningDraft);corrupt.contracts[0].goal='CORRUPTED TEST ONLY';await s.save(record,{...record,planningDraft:corrupt});let calls=0;await assert.rejects(step(s,b.id,'',async()=>{calls++;}),/校验失败/);assert.equal(calls,0);
});
test('暂停中的规划最多保存本批，后续云端不再请求；恢复沿用检查点',async()=>{
  const s=fresh(),b=await book(s,1000,100),secret=await configured(s);await startJob(s,b.id,3);await tickRunner(s.db,secret,batchedFixture);let release;const gate=new Promise(r=>release=r);
  const pending=runJobStep(s,b.id,secret,async(...a)=>{await gate;return batchedFixture(...a);});await new Promise(r=>setTimeout(r,20));await pauseJob(s,b.id);release();await pending;
  assert.equal((await s.get(b.id)).status,'paused');assert.equal((await s.get(b.id)).planningDraft.contracts.length,10);let calls=0;await tickRunner(s.db,secret,async()=>{calls++;});assert.equal(calls,0);
  await startJob(s,b.id,3);await tickRunner(s.db,secret,batchedFixture);assert.equal((await s.get(b.id)).planningDraft.contracts.length,20);
});
test('未完成规划进入备份，恢复后默认暂停；损坏规划在创建副本前拒绝',async()=>{
  const s=fresh(),b=await book(s,9000,100);for(let i=0;i<3;i++)await step(s,b.id,'',batchedFixture);const backup={format:'novel-factory-backup-v1',book:await s.get(b.id),chapters:[],versions:[]};
  const restored=await restoreBackup(s,backup,crypto.randomUUID());assert.equal(restored.status,'paused');assert.deepEqual(restored.planningDraft,backup.book.planningDraft);await startJob(s,restored.id,3).catch(e=>assert.match(e.message,/请先保存/));
  await configured(s);await startJob(s,restored.id,3);await runJobStep(s,restored.id,'',batchedFixture);assert.equal((await s.get(restored.id)).planningDraft.contracts.length,30);
  const damaged=structuredClone(backup);damaged.book.planningDraft.contracts[0].title='CORRUPTED TEST ONLY';await assert.rejects(restoreBackup(s,damaged,crypto.randomUUID()),/校验失败/);assert.equal((await s.list('book')).length,2);
});
test('旧版完整大纲直接续写，不重做选题或分批计划',async()=>{
  const s=fresh(),b=await book(s,1000,100);await s.save(b,{...b,plan:plan(100),status:'ready'});let role;await step(s,b.id,'',async(...a)=>{role=a[4];return fixture(...a);});assert.equal(role,'contract');assert.equal((await s.list('chapter',b.id)).length,1);assert.equal((await s.get(b.id)).planningDraft,undefined);
});
test('分批规划仍受预算和费用授权门控制，失败后不无限请求或丢失前批',async()=>{
  const s=fresh(),b=await book(s,1000,100),secret=await configured(s,{taskLimit:.000001});await step(s,b.id,'',batchedFixture);const before=(await s.get(b.id)).planningDraft;await startJob(s,b.id,3);let calls=0;
  await tickRunner(s.db,secret,(...a)=>modelCall(...a,async()=>{calls++;throw new Error('HTTP should not be reached');}));assert.equal((await s.get(b.id+':job')).status,'blocked');assert.deepEqual((await s.get(b.id)).planningDraft,before);assert.equal(calls,0);await tickRunner(s.db,secret,async()=>{calls++;});assert.equal(calls,0);
});
test('长篇场景规划不反复发送300章全部合同，保留圣经、已锁事实与相邻计划',()=>{
  const p=plan(300);p.contracts[299].goal='DISTANT CONTRACT TEST ONLY';p.bible.ending='CANONICAL ENDING TEST ONLY';
  const prompt=contractPrompt({plan:p,targetWords:9000},{facts:{known:'LOCKED FACT TEST ONLY'},ledger:[],foreshadowing:[]},p.contracts[99]);
  assert.ok(!prompt.includes('DISTANT CONTRACT TEST ONLY'));assert.ok(prompt.includes('CANONICAL ENDING TEST ONLY'));assert.ok(prompt.includes('LOCKED FACT TEST ONLY'));assert.ok(prompt.includes(p.contracts[100].goal));assert.ok(prompt.length<JSON.stringify(p).length);
});
test('预算修改不自动开启费用或重启任务；他人、过期版本与在途检查点不能修改',async()=>{
  const s=fresh(),b=await book(s),secret=await configured(s);await startJob(s,b.id,3);await assert.rejects(setBookBudget(s,{id:b.id,revision:b.revision,budget:40}),/先暂停/);await pauseJob(s,b.id);const current=await s.get(b.id);
  await assert.rejects(setBookBudget(s,{id:b.id,revision:b.revision,budget:40}),/版本已变化/);const other=new Store(s.db,'other-user');await assert.rejects(setBookBudget(other,{id:b.id,revision:current.revision,budget:40}),/作品不存在/);
  await settings(s,{spendEnabled:false},secret);const saved=await setBookBudget(s,{id:b.id,revision:current.revision,budget:40});assert.equal(saved.budget,40);assert.equal(saved.status,'paused');assert.equal((await s.get(b.id+':job')).status,'paused');assert.equal((await config(s)).spendEnabled,false);
  await assert.rejects(setBookBudget(s,{id:b.id,revision:saved.revision,budget:-1}),/0到10000/);await s.create('chapter',{number:1,lease:{until:Date.now()+10000}},b.id);await assert.rejects(setBookBudget(s,{id:b.id,revision:saved.revision,budget:50}),/尚未完成/);
});
