'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
export default function PlanEditor({book,chapters,active,busy,onSave}:any){
  const [editing,setEditing]=useState(false),[draft,setDraft]=useState<any>(null),[number,setNumber]=useState(1);
  useEffect(()=>{setEditing(false);setDraft(null);},[book.id]);
  const first=Math.max(0,...chapters.map((c:any)=>c.number))+1;
  function begin(){setDraft({id:book.id,revision:book.revision,contracts:structuredClone(book.plan.contracts),arcs:structuredClone(book.plan.arcs),guidance:book.guidance||''});setNumber(Math.min(first,book.totalChapters));setEditing(true);}
  const c=draft?.contracts[number-1];
  function changeContract(k:string,v:string){setDraft({...draft,contracts:draft.contracts.map((x:any)=>x.number===number?{...x,[k]:v}:x)});}
  return <section className="card full-width outline-control"><div className="section-title"><h2>控制后续剧情 · 大纲V{book.planRevision||1}</h2><Button variant="outline" onClick={begin} disabled={active||busy||first>book.totalChapters}>编辑未来大纲</Button></div><p className="small-note">先暂停任务并等待当前检查点保存。已经开始的第1–{first-1}章合同及已发生事实受保护，修改从第{first}章起生效；正文会沿用正式审核门。</p>{active&&<p>云端任务进行中，请在创作控制台暂停后编辑。</p>}{!editing&&book.guidance&&<p>后续创作要求：{book.guidance}</p>}{editing&&draft&&<div className="outline-form"><label className="field"><span>对后续剧情的整体要求</span><Textarea maxLength={4000} value={draft.guidance} onChange={e=>setDraft({...draft,guidance:e.target.value})} placeholder="例如：下一阶段把冲突从调查转向利益谈判，主角必须承担真实代价。不得修改已发生的事实。"/></label><label className="field"><span>选择尚未开始的章节</span><select aria-label="待修改的章节计划" value={number} onChange={e=>setNumber(Number(e.target.value))}>{draft.contracts.filter((x:any)=>x.number>=first).map((x:any)=><option key={x.number} value={x.number}>第{x.number}章 · {x.title}</option>)}</select></label>{c&&<div className="form-grid">{[['title','章节标题'],['goal','本章必须推进的目标'],['method','冲突与解决方式'],['consequence','不可删掉的后果']].map(([k,label])=><label className="field" key={k}><span>{label}</span>{k==='title'?<Input maxLength={2000} value={c[k]} onChange={e=>changeContract(k,e.target.value)}/>:<Textarea maxLength={2000} value={c[k]} onChange={e=>changeContract(k,e.target.value)}/>}</label>)}</div>}<details><summary>编辑尚未开始的阶段计划</summary>{draft.arcs.filter((a:any)=>a.start>=first).map((a:any)=><div className="arc-edit" key={a.id}><h3>第{a.start}–{a.end}章</h3>{[['goal','阶段目标'],['irreversibleChange','阶段不可逆变化']].map(([k,label])=><label className="field" key={k}><span>{label}</span><Textarea maxLength={2000} value={a[k]} onChange={e=>setDraft({...draft,arcs:draft.arcs.map((x:any)=>x.id===a.id?{...x,[k]:e.target.value}:x)})}/></label>)}</div>)}</details><div className="button-row"><Button disabled={busy||active} onClick={async()=>{if(await onSave(draft))setEditing(false);}}>保存大纲新版本</Button><Button variant="ghost" disabled={busy} onClick={()=>setEditing(false)}>取消编辑</Button><a href={'/api/workspace?planVersions='+encodeURIComponent(book.id)} target="_blank" rel="noopener noreferrer">查看已保存的大纲历史</a></div></div>}</section>;
}
