export function planningPrompt(book,platforms,feedback,staged=false) {
  const input={title:book.title,direction:book.direction,platform:book.platform,totalChapters:book.totalChapters,targetWords:book.targetWords,budget:book.budget};
  return `独立策划原创商业长篇。用户方向 ${JSON.stringify(input)}。平台事实和缺失项 ${JSON.stringify(platforms)}。以往真实投稿反馈 ${JSON.stringify(feedback)}。禁止虚构热度和市场样本。题材机会属于判断，写明证据或假设及置信度。默认推荐平台为暂定主平台，AI政策未核实不得认定可投稿。总章节${book.totalChapters}，每章${book.targetWords}汉字。三种以上真正不同的故事发动机，选择一个，说明成本、竞争风险、长篇扩展性。人物各有独立目标、欲望、弱点、习惯、语言、代价和信息边界。中段阶段要有不可逆变化；阶段id唯一，范围从1到${book.totalChapters}连续无重叠无缺口，通常每10章一阶段。${staged?'本次只设计故事圣经和全书阶段，不输出逐章contracts；逐章合同随后每10章单独规划并保存。':'本次设计完整故事和逐章合同。'}只返回JSON：{title,platform,candidates:[{title,engine,genre,appeal,risks,score,confidence,costReason}],selectionReason,bible:{premise,engine,world,rules,mainConflict,ending},style:{narration,dialogue,avoid},characters:[{name,goal,desire,weakness,habit,voice,cost,knowledge,relationships}],facts:{稳定事实键:值},foreshadowing:[{id,promise,dueChapter}],arcs:[{id,start,end,goal,irreversibleChange,payoff}]${staged?'':',contracts:[{number,title,goal,cause,conflict,method,consequence,emotion,hook}]'}}。${staged?'故事与阶段必须覆盖整本书，不能仅设计开头。每个字段简明具体，避免重复解释。':`contracts必须覆盖第1到${book.totalChapters}章全部，按顺序，一章一项。`}`;
}
export function planningBatchPrompt(book,draft,range) {
  const previous=draft.contracts.slice(-10);
  const arcSummaries=draft.contracts.filter(c=>draft.outline.arcs.some(a=>a.end===c.number)).map(c=>({number:c.number,consequence:c.consequence}));
  return `继续同一本原创长篇的逐章规划。方向${book.direction}，主平台${book.platform}，每章${book.targetWords}汉字。故事圣经、人物、稳定事实、全书阶段已保存且不可替换：${JSON.stringify(draft.outline)}。此前阶段结束时的后果${JSON.stringify(arcSummaries)}。最近10章已保存合同${JSON.stringify(previous)}。本次只规划第${range.start}到${range.end}章，按顺序一章一项，不输出以前或以后的章节。所属阶段${JSON.stringify(range.arc)}。承接前章的因果与代价，体现人物自主目标和信息边界，不恢复既有损失；本阶段结束章必须兑现阶段目标及不可逆变化。检查冲突、手段与情绪组合，禁止循环换皮；删去任一章应产生可说明的实质损失。只返回JSON {contracts:[{number,title,goal,cause,conflict,method,consequence,emotion,hook}]}，所有文字字段必须是具体非空字符串，单字段不超过2000字。不得更改故事圣经、平台或已保存合同。`;
}
export function contractPrompt(book,memory,previous) {
  const p=book.plan,context={title:p.title,bible:p.bible,style:p.style,characters:p.characters,foreshadowing:p.foreshadowing,arcs:p.arcs.filter(a=>a.end>=previous.number-10&&a.start<=previous.number+10),contracts:p.contracts.filter(c=>c.number>=previous.number-2&&c.number<=previous.number+2)};
  return `制定下一章场景合同。遵循已锁事实与人物信息边界。用户对未来剧情的要求（不改变已发生事实）：${previous.number>=(book.guidanceFromChapter||1)?book.guidance||'遵循原计划':'遵循原计划'}。故事骨架与当前附近计划${JSON.stringify(context)}；本章预合同${JSON.stringify(previous)}；已锁记忆${JSON.stringify(memory)}。正文目标${book.targetWords}汉字，分${Math.ceil(book.targetWords/1600)}段，每段有实际推进。最近重复结构必须变更。本章无法推进时返回{blocked:true,reason}。否则只返回JSON {title,goal,deleteLoss,scenes:[{goal,conflict,choice,consequence,characters,setting,knowledgeBoundary}],requiredDelta,forbidden,hook}。场景数必须等于${Math.ceil(book.targetWords/1600)}。`;
}
export function writePrompt(book,chapter,memory,revision=false) {
  const i=chapter.chunks.length;
  return `原创中文商业小说正文，禁止抄袭或模仿特定作者。用户对未来剧情的要求：${chapter.number>=(book.guidanceFromChapter||1)?book.guidance||'遵循原计划':'遵循原计划'}。圣经${JSON.stringify(book.plan.bible)}；文风${JSON.stringify(book.plan.style)}；人物${JSON.stringify(book.plan.characters)}；锁定记忆${JSON.stringify(memory)}；本章合同${JSON.stringify(chapter.contract)}；已完成正文${chapter.chunks.join('\n\n')}。只写第${i+1}/${chapter.contract.scenes.length}片段：${JSON.stringify(chapter.contract.scenes[i])}，目标${Math.ceil(book.targetWords/chapter.contract.scenes.length)}汉字。衔接前文，不重复，不复述；不用片段标题。人物通过动作、选择、对话体现差异，保留言外之意。不能靠机械反转、巧合救场、字数填充。${revision?'返修意见：'+JSON.stringify(chapter.repairIssues):''}。只返回JSON {text,sceneComplete:true}。`;
}
export function reviewPrompt(book,chapter,memory,past) {
  return `独立编辑审阅实际全文，拒绝自夸评分。主平台${book.platform}；圣经${JSON.stringify(book.plan.bible)}；人物${JSON.stringify(book.plan.characters)}；已锁事实及伏笔${JSON.stringify(memory)}；本章合同${JSON.stringify(chapter.contract)}；最近结构${JSON.stringify(past.map(c=>({number:c.number,summary:c.review?.summary,signature:c.review?.signature})))}。全文：\n${chapter.content}\n评分商业20、因果20、人物20、节奏15、语言15、原创完成10；85且核心各14才通过。每项必须引用全文原句并说明理由。重大矛盾、人物失真、注水、重复结构、设定冲突、原创风险为fatal或major，高分不能掩盖。语义重复与历史摘要比较；当前工具不能证明全网原创。执行删除测试。状态变化key/from/to精确匹配锁定事实，新增key的from为null。伏笔兑现须有事件证据。只返回JSON {scores:{commercial:{score,quote,reason},causality:{score,quote,reason},character:{score,quote,reason},pace:{score,quote,reason},language:{score,quote,reason},originality:{score,quote,reason}},issues:[{severity:"fatal|major|minor",message,quote,fix}],deleteTest:{necessary:true,loss},summary,signature:{conflict,solution,emotion},changes:[{key,from,to,reason,quote}],foreshadowing:[{id,status:"open|paid",evidence}],consequences,questions,architectureConcern:null}。`;
}
