// HTTP integration QA of actual built Worker; no external provider calls.
import {createRequire} from 'node:module';
import {readFileSync,readdirSync} from 'node:fs';
import {resolve,join} from 'node:path';
import assert from 'node:assert/strict';
import {newPlanningDraft,appendPlanningBatch} from '../lib/planning.mjs';
const require=createRequire(import.meta.url),wranglerRequire=createRequire(require.resolve('wrangler/package.json'));
const {Miniflare}=wranglerRequire('miniflare');
const root=resolve('dist/server'),walk=d=>readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(join(d,e.name)):[join(d,e.name)]);
const files=walk(root).filter(f=>f.endsWith('.js')).sort((a,b)=>a===join(root,'index.js')?-1:b===join(root,'index.js')?1:0);
const secret=btoa(String.fromCharCode(...crypto.getRandomValues(new Uint8Array(32))));
const mf=new Miniflare({modules:files.map(path=>({type:'ESModule',path})),compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],bindings:{DATA_ENCRYPTION_KEY:secret,CLOUD_RUNNER_ENABLED:'1'}});
const ownerHeaders={'oai-authenticated-user-id':'integration-test-owner'};
async function post(x,headers=ownerHeaders){return mf.dispatchFetch('https://test.invalid/api/workspace',{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify(x)});}
try {
  await mf.ready;const db=await mf.getD1Database('DB');
  for(const sql of readFileSync('drizzle/0000_rare_tenebrous.sql','utf8').split('--> statement-breakpoint'))await db.exec(sql.replace(/\n/g,' '));
  const rootPage=await mf.dispatchFetch('https://test.invalid/');assert.equal(rootPage.status,200);const html=await rootPage.text();assert.ok(html.includes('AI商业小说工厂')&&html.includes('连接创作工作台'));console.log('PASS built Worker root HTML and app shell');
  const anon=await mf.dispatchFetch('https://test.invalid/api/workspace');assert.equal(anon.status,401);console.log('PASS missing identity rejected');
  const invalidOrigin=await post({action:'create',key:crypto.randomUUID(),input:{}},{...ownerHeaders,Origin:'https://other.invalid'});assert.equal(invalidOrigin.status,403);console.log('PASS cross-origin writes rejected');
  const key=crypto.randomUUID();const r=await post({action:'create',key,input:{title:'HTTP INTEGRATION TEST ONLY'}});assert.equal(r.status,200);const b=(await r.json()).result;assert.equal(b.totalChapters,100);const again=await post({action:'create',key,input:{}});assert.equal((await again.json()).result.id,b.id);console.log('PASS actual API project creation and idempotency');
  const settings=await post({action:'settings',input:{apiKey:'integration-dummy-key'}});assert.equal(settings.status,200);assert.ok(!(await settings.text()).includes('integration-dummy-key'));const plain=await db.prepare("SELECT data FROM records WHERE kind='settings'").first();assert.ok(!plain.data.includes('integration-dummy-key'));console.log('PASS API secret encryption and read redaction');
  const generation=await post({action:'step',id:b.id});assert.equal(generation.status,400);assert.match((await generation.json()).error,/费用调用尚未开启/);assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM calls').first()).n,0);console.log('PASS generation without spending approval makes no billable calls');
  const list=await mf.dispatchFetch('https://test.invalid/api/workspace',{headers:ownerHeaders});assert.equal((await list.json()).books.length,1);const other=await mf.dispatchFetch('https://test.invalid/api/workspace',{headers:{'oai-authenticated-user-id':'other-owner'}});assert.equal((await other.json()).books.length,0);console.log('PASS persisted API state and owner isolation');
  const pwa=JSON.parse(readFileSync('public/manifest.webmanifest','utf8'));for(const icon of pwa.icons)assert.ok(readFileSync('public'+icon.src).length>100);console.log('PASS PWA manifest and both real PNG icons');
  const guide=await mf.dispatchFetch('https://test.invalid/guide');assert.equal(guide.status,200);const guideHTML=await guide.text();assert.ok(guideHTML.includes('火山方舟')&&guideHTML.includes('每小时')&&guideHTML.includes('编辑未来大纲'));console.log('PASS real guide route with model, installation and cloud-run instructions');
  const missingKey=await post({action:'startJob',id:b.id,target:3});assert.equal(missingKey.status,400);assert.match((await missingKey.json()).error,/请先保存/);console.log('PASS cloud job requires model configuration and spending consent');
  const runnerTick=await mf.dispatchFetch('https://test.invalid/api/runner',{method:'POST',headers:{'Content-Type':'application/json'},body:'{"action":"tick"}'});assert.equal(runnerTick.status,200);assert.equal((await runnerTick.json()).stopReason,'idle');const heartbeat=await mf.dispatchFetch('https://test.invalid/api/runner');assert.ok((await heartbeat.json()).runner.lastTick);assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM calls').first()).n,0);console.log('PASS service writer heartbeat persists without browser or model request');
  const browserTick=await mf.dispatchFetch('https://test.invalid/api/runner',{method:'POST',headers:{Origin:'https://test.invalid','Content-Type':'application/json'},body:'{"action":"tick"}'});assert.equal(browserTick.status,403);const forgedTask=await mf.dispatchFetch('https://test.invalid/api/runner',{method:'POST',headers:{'Content-Type':'application/json'},body:'{"action":"tick","owner":"other"}'});assert.equal(forgedTask.status,400);console.log('PASS service runner rejects browser calls and arbitrary task parameters');
  const doubao=await post({action:'settings',input:{provider:'doubao',model:'HTTP TEST ONLY / copy your actual model ID',apiKey:'integration-doubao-dummy'}});assert.equal(doubao.status,200);const savedCfg=(await doubao.json()).result;assert.equal(savedCfg.provider,'doubao');assert.equal(savedCfg.hasKey,true);assert.ok(!JSON.stringify(savedCfg).includes('integration-doubao-dummy'));console.log('PASS Doubao configuration through real Worker API with encrypted key');
  const conn=await post({action:'testConnection'});assert.equal(conn.status,400);assert.match((await conn.json()).error,/尚未开启/);assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM calls').first()).n,0);console.log('PASS connection test blocks unapproved billable request');
  const state=await (await mf.dispatchFetch('https://test.invalid/api/workspace',{headers:ownerHeaders})).json(),current=state.books[0];
  const budgetChange=await post({action:'bookBudget',input:{id:b.id,revision:current.revision,budget:25}});assert.equal(budgetChange.status,200);const budgetBook=(await budgetChange.json()).result;assert.equal(budgetBook.budget,25);assert.equal((await (await mf.dispatchFetch('https://test.invalid/api/workspace',{headers:ownerHeaders})).json()).settings.spendEnabled,false);assert.equal((await db.prepare("SELECT COUNT(*) AS n FROM records WHERE kind='job'").first()).n,0);console.log('PASS owner budget change neither enables spending nor starts job');
  const staleBudget=await post({action:'bookBudget',input:{id:b.id,revision:current.revision,budget:40}});assert.equal(staleBudget.status,400);const foreignBudget=await post({action:'bookBudget',input:{id:b.id,revision:budgetBook.revision,budget:40}},{'oai-authenticated-user-id':'other-owner'});assert.equal(foreignBudget.status,400);console.log('PASS budget stale version and other owner rejected');
  const outline={title:'HTTP SYNTHETIC PLANNING FIXTURE ONLY',platform:'番茄小说',candidates:[{engine:'甲机制'},{engine:'乙机制'},{engine:'丙机制'}],bible:{premise:'TEST ONLY / not a fiction quality sample'},style:{narration:'合成'},characters:[{name:'甲'},{name:'乙'},{name:'丙'},{name:'丁'}],facts:{},arcs:Array.from({length:10},(_,i)=>({id:i+1,start:i*10+1,end:i*10+10,goal:'测试目标'+i,irreversibleChange:'测试后果'+i}))};
  const contracts=Array.from({length:10},(_,i)=>({number:i+1,title:'测试'+i,goal:'目标'+i,cause:'因果'+i,conflict:'冲突'+i,method:'方法'+i,consequence:'后果'+i,emotion:'情绪'+i,hook:'问题'+i}));const draft=await appendPlanningBatch(await newPlanningDraft(outline,100),{contracts});await db.prepare('UPDATE records SET data=? WHERE id=?').bind(JSON.stringify({...budgetBook,plan:null,planningDraft:draft}),b.id).run();
  const backup=await (await mf.dispatchFetch('https://test.invalid/api/workspace?backup='+encodeURIComponent(b.id),{headers:ownerHeaders})).json();assert.equal(backup.book.planningDraft.contracts.length,10);const restore=await post({action:'restore',input:backup,key:crypto.randomUUID()});assert.equal(restore.status,200);const restored=(await restore.json()).result;assert.equal(restored.status,'paused');assert.equal(restored.planningDraft.hash,draft.hash);assert.equal((await db.prepare("SELECT COUNT(*) AS n FROM records WHERE kind='chapter'").first()).n,0);console.log('PASS partial planning backup/restore through built API, paused and no premature fiction');
  backup.book.planningDraft.contracts[0].goal='CORRUPTED TEST ONLY';const damaged=await post({action:'restore',input:backup,key:crypto.randomUUID()});assert.equal(damaged.status,400);assert.match((await damaged.json()).error,/校验失败/);assert.equal((await db.prepare("SELECT COUNT(*) AS n FROM records WHERE kind='book'").first()).n,2);console.log('PASS damaged planning checkpoint rejected before creating a book');
  console.log('HTTP integration checks: 18 passed. Browser interaction, real provider response and live model quality not tested.');
} finally {await mf.dispose();}
